apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-fuzz-pipeline
spec:
  params:
    - name: package
      type: string
      default: "github.com/jerop/fuzzton"
    - name: target
      type: string
      default: "."
    - name: flags
      type: string
      default: "-fuzztime=30m"
  workspaces:
    - name: workarea
      description: The workspace where the repo will be cloned
  results:
    - name: commit-sha
      description: the sha of the commit that was used
      value: $(tasks.clone.results.commit)
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workarea
          subpath: git
      params:
        - name: url
          value: https://$(params.package)
    - name: test
      runAfter: [clone]
      taskRef:
        name: golang-test
      params:
        - name: package
          value: $(params.package)
      workspaces:
        - name: source
          workspace: workarea
          subpath: git
    - name: fuzz
      runAfter: [test]
      taskRef:
        name: golang-fuzz
      params:
        - name: package
          value: $(params.package)
        - name: target
          value: $(params.target)
        - name: flags
          value: $(params.flags)
      workspaces:
        - name: source
          workspace: workarea
          subpath: git
